# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db28e9c5cc5037b681acbd8c457f444010e67890bbd0e18cb326b95193fa6417c20abdcd0f21504a914723283eed7718011e77de13505a687bd743ccf618c48c

test:
  secret_key_base: 79f1347456660cc1e4373b64190f8af29d7676d9400271a2326400ed2281b6b0b3a161c7c5d1ccac71cceb207bf3b45abe81ddccf60b8de7f835b1bc7052ca60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
